"""SFT warmup training using HuggingFace Trainer.

Trains on positions generated by sft_data_gen.py. Checkpoints at best
validation accuracy (% of outputs where parsed move matches label move).
"""

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List

import numpy as np


def load_data(data_path: str) -> tuple:
    """Load JSONL data and split into train/val.

    Args:
        data_path: Path to the JSONL file from sft_data_gen.py.

    Returns:
        Tuple of (train_data, val_data) as lists of dicts.
    """
    data_path = Path(data_path)
    meta_path = data_path.parent / "sft_warmup_meta.json"

    records = []
    with open(data_path) as f:
        for line in f:
            records.append(json.loads(line))

    if meta_path.exists():
        with open(meta_path) as f:
            meta = json.load(f)
        train_end = meta["train_range"][1]
    else:
        train_end = int(len(records) * 0.9)

    return records[:train_end], records[train_end:]


def extract_label_move(completion: str) -> int:
    """Extract the move integer from a completion string.

    Args:
        completion: Completion string with <move> tag.

    Returns:
        Move column as integer, or -1 if not found.
    """
    match = re.search(r"<move>\s*(\d)\s*</move>", completion)
    if match:
        return int(match.group(1))
    return -1


def compute_move_accuracy(predictions: List[str], labels: List[str]) -> float:
    """Compute percentage of predictions matching label moves.

    Args:
        predictions: List of model output strings.
        labels: List of completion strings with <move> tags.

    Returns:
        Accuracy as float in [0, 1].
    """
    correct = 0
    total = len(labels)
    for pred, label in zip(predictions, labels):
        pred_move = extract_label_move(pred)
        label_move = extract_label_move(label)
        if pred_move == label_move and label_move != -1:
            correct += 1
    return correct / total if total > 0 else 0.0


def train(
    model_name: str = "Qwen/Qwen3-4B-Base",
    data_path: str = "data/sft_warmup.jsonl",
    output_dir: str = "checkpoints/condition_a",
    epochs: int = 3,
    batch_size: int = 8,
    lr: float = 2e-5,
    device: str = "auto",
) -> None:
    """Run SFT training.

    Args:
        model_name: HuggingFace model name or path.
        data_path: Path to JSONL training data.
        output_dir: Directory for checkpoints.
        epochs: Number of training epochs.
        batch_size: Per-device batch size.
        lr: Learning rate.
        device: Device string ('auto', 'cpu', 'cuda').
    """
    try:
        import torch
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
        from datasets import Dataset
    except ImportError as e:
        print(f"Required package not installed: {e}")
        print("Install with: pip install torch transformers datasets")
        return

    # Device handling
    if device == "auto":
        if torch.cuda.is_available():
            device = "cuda"
        else:
            device = "cpu"
            print("WARNING: Running on CPU. Training will be very slow.")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Load data
    print(f"Loading data from {data_path}...")
    train_data, val_data = load_data(data_path)
    print(f"Train: {len(train_data)}, Val: {len(val_data)}")

    # Load tokenizer and model
    print(f"Loading model: {model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        trust_remote_code=True,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    )

    # Prepare datasets
    def tokenize_fn(examples: Dict) -> Dict:
        texts = [p + c for p, c in zip(examples["prompt"], examples["completion"])]
        tokenized = tokenizer(
            texts,
            truncation=True,
            max_length=512,
            padding="max_length",
        )
        tokenized["labels"] = tokenized["input_ids"].copy()
        return tokenized

    train_ds = Dataset.from_list(train_data)
    val_ds = Dataset.from_list(val_data)

    train_ds = train_ds.map(tokenize_fn, batched=True, remove_columns=train_ds.column_names)
    val_ds = val_ds.map(tokenize_fn, batched=True, remove_columns=val_ds.column_names)

    # Training arguments
    training_args = TrainingArguments(
        output_dir=str(output_path),
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_steps=100,
        learning_rate=lr,
        warmup_ratio=0.1,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        report_to="none",
        fp16=(device == "cuda"),
    )

    # Train
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        tokenizer=tokenizer,
    )

    print("Starting training...")
    trainer.train()

    # Save best model
    trainer.save_model(str(output_path / "best"))
    tokenizer.save_pretrained(str(output_path / "best"))

    # Compute validation accuracy
    print("\nComputing validation move accuracy...")
    model.eval()
    correct = 0
    total = 0
    val_raw = load_data(data_path)[1]

    for record in val_raw[:500]:  # Sample for speed
        inputs = tokenizer(record["prompt"], return_tensors="pt", truncation=True, max_length=256)
        inputs = {k: v.to(model.device) for k, v in inputs.items()}
        with torch.no_grad():
            outputs = model.generate(**inputs, max_new_tokens=64, do_sample=False)
        pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
        pred_move = extract_label_move(pred)
        label_move = extract_label_move(record["completion"])
        if pred_move == label_move and label_move != -1:
            correct += 1
        total += 1

    accuracy = correct / total if total > 0 else 0.0
    print(f"\nValidation move accuracy: {accuracy:.3f} ({correct}/{total})")

    if accuracy < 0.35:
        print("WARNING: Insufficient warmup — do not proceed to RL")
    if accuracy > 0.65:
        print("WARNING: Possible overfitting — use earlier checkpoint")

    print(f"\nCheckpoints saved to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SFT warmup training")
    parser.add_argument("--model", type=str, default="Qwen/Qwen3-4B-Base", help="Model name/path")
    parser.add_argument("--data", type=str, default="data/sft_warmup.jsonl", help="Training data")
    parser.add_argument("--output_dir", type=str, default="checkpoints/condition_a", help="Output dir")
    parser.add_argument("--epochs", type=int, default=3, help="Training epochs")
    parser.add_argument("--batch_size", type=int, default=8, help="Batch size")
    parser.add_argument("--lr", type=float, default=2e-5, help="Learning rate")
    parser.add_argument("--device", type=str, default="auto", help="Device (auto/cpu/cuda)")
    args = parser.parse_args()

    train(
        model_name=args.model,
        data_path=args.data,
        output_dir=args.output_dir,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        device=args.device,
    )
